using System.Text;
using System.Text.Json;
using QuickJack.Core.Models;
using QuickJack.Core.Storage;

namespace QuickJack.Core.Execution;

/// <summary>
/// The scratch directory backing one elevated run: the user's script, the wrapper that
/// runs it, the redirected output files, and the cancel/exit sentinels.
/// </summary>
internal sealed class ElevatedRunFiles : IDisposable
{
    private ElevatedRunFiles(string directory) => Directory = directory;

    public string Directory { get; }

    public string ScriptPath { get; private set; } = string.Empty;
    public string WrapperPath => Path.Combine(Directory, "wrapper.ps1");
    public string EnvironmentPath => Path.Combine(Directory, "env.json");
    public string StdOutPath => Path.Combine(Directory, "stdout.log");
    public string StdErrPath => Path.Combine(Directory, "stderr.log");
    public string CancelPath => Path.Combine(Directory, "cancel");
    public string ExitPath => Path.Combine(Directory, "exit");

    public bool CancelRequested { get; private set; }

    public static ElevatedRunFiles Create(string runId)
    {
        var directory = Path.Combine(ScriptWriter.Directory, $"run-{runId}");
        System.IO.Directory.CreateDirectory(directory);

        // %TEMP% is already user-scoped, but this run carries an elevated process's output;
        // pinning the ACL means a later change to TEMP's inherited permissions cannot widen it.
        WindowsAcl.TryRestrictToCurrentUser(directory);

        return new ElevatedRunFiles(directory);
    }

    public void WriteScript(ShellKind shell, string script)
    {
        var temp = ScriptWriter.Write(shell, script);
        ScriptPath = Path.Combine(Directory, "script" + ScriptWriter.Extension(shell));
        File.Move(temp.Path, ScriptPath, overwrite: true);
    }

    public void WriteWrapper(CommandDef command, BoundScript bound, string executable)
    {
        // Parameter values are written as JSON data, never interpolated into the wrapper's
        // source. Generating PowerShell that embeds user values would reintroduce exactly
        // the injection problem ParameterBinder exists to prevent.
        File.WriteAllText(
            EnvironmentPath,
            JsonSerializer.Serialize(bound.Environment),
            new UTF8Encoding(false));

        var arguments = string.Join(", ",
            ShellInfo.Arguments(command.Shell, ScriptPath).Select(Ps.Quote));

        var workingDirectory =
            !string.IsNullOrWhiteSpace(command.WorkingDirectory) &&
            System.IO.Directory.Exists(command.WorkingDirectory)
                ? command.WorkingDirectory
                : Directory;

        // $$ raw string: {{ }} delimit interpolation, so PowerShell's own braces stay literal.
        var wrapper = $$"""
            # Generated by QuickJack. Runs elevated; the launching widget does not.
            $ErrorActionPreference = 'Stop'
            $exitPath   = {{Ps.Quote(ExitPath)}}
            $cancelPath = {{Ps.Quote(CancelPath)}}
            $code = 1

            try {
                foreach ($p in (Get-Content -Raw -LiteralPath {{Ps.Quote(EnvironmentPath)}} |
                                ConvertFrom-Json).PSObject.Properties) {
                    [Environment]::SetEnvironmentVariable($p.Name, [string]$p.Value)
                }
                [Environment]::SetEnvironmentVariable('QUICKJACK', '1')
                [Environment]::SetEnvironmentVariable('QUICKJACK_ELEVATED', '1')

                $child = Start-Process -FilePath {{Ps.Quote(executable)}} `
                    -ArgumentList @({{arguments}}) `
                    -WorkingDirectory {{Ps.Quote(workingDirectory)}} `
                    -RedirectStandardOutput {{Ps.Quote(StdOutPath)}} `
                    -RedirectStandardError {{Ps.Quote(StdErrPath)}} `
                    -NoNewWindow -PassThru

                # Touching .Handle caches the process handle. Without it PowerShell lets the
                # handle go and $child.ExitCode reads back as 0 no matter what the process
                # actually returned.
                $null = $child.Handle

                # The widget runs at medium integrity and cannot kill this child, so we
                # watch for its cancel sentinel and do it here.
                while (-not $child.HasExited) {
                    if (Test-Path -LiteralPath $cancelPath) {
                        # /T so the whole tree goes, not just the interpreter.
                        & taskkill.exe /PID $child.Id /T /F 2>&1 | Out-Null
                        break
                    }
                    Start-Sleep -Milliseconds 150
                }

                $child.WaitForExit()
                $code = $child.ExitCode
            }
            catch {
                $_ | Out-String | Add-Content -LiteralPath {{Ps.Quote(StdErrPath)}} -Encoding utf8
                $code = 1
            }
            finally {
                Set-Content -LiteralPath $exitPath -Value $code -Encoding ascii
            }

            exit $code
            """;

        File.WriteAllText(WrapperPath, wrapper, new UTF8Encoding(true));
    }

    public void RequestCancel()
    {
        try
        {
            File.WriteAllText(CancelPath, "1");
            CancelRequested = true;
        }
        catch (IOException) { }
        catch (UnauthorizedAccessException) { }
    }

    public int? ReadExitCode()
    {
        try
        {
            return File.Exists(ExitPath) && int.TryParse(File.ReadAllText(ExitPath).Trim(), out var code)
                ? code
                : null;
        }
        catch (IOException) { return null; }
        catch (UnauthorizedAccessException) { return null; }
    }

    public void Dispose()
    {
        try { System.IO.Directory.Delete(Directory, recursive: true); }
        catch (IOException) { }
        catch (UnauthorizedAccessException) { }
    }
}

/// <summary>PowerShell literal quoting.</summary>
internal static class Ps
{
    /// <summary>
    /// A single-quoted PowerShell string. Doubling the quote is the complete escape —
    /// single-quoted strings process no other escape sequences, so nothing inside can
    /// break out into code.
    /// </summary>
    public static string Quote(string value) => "'" + value.Replace("'", "''") + "'";
}
